
name: CI workflow

on:
  push:
    # Only on push of commits, not push of tags (we have 'release' for that)
    branches:
      - "*"
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java and Maven settings
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          server-id: maven-central # Value of <id> in <server> section of generated settings.xml
          server-username: 'MAVEN_CENTRAL_USERNAME' # env variable name for username in <server> section of generated settings.xml
          server-password: 'MAVEN_CENTRAL_PASSWORD' # env variable name for password in <server> section of generated settings.xml

      - name: Maven execution
        run: |
          ./mvnw \
            --show-version \
            --batch-mode \
            --no-transfer-progress \
            -Dci.project.url="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" \
            -Dci.scm.tag="${GITHUB_REF_NAME}" \
            -Drevision="${GITHUB_REF_NAME#v}" \
            -P$MVN_PROFILES \
              $MVN_PHASE
        env:
          MVN_PHASE: ${{ github.event_name == 'release' && 'deploy' || 'verify' }}
          MVN_PROFILES: ${{ github.event_name == 'release' && '"publish"' || '""' }}
          # The following 2 env vars are used by the Maven GPG Plugin
          MAVEN_GPG_KEY: ${{ secrets.MAVEN_CENTRAL_GPG_SECRET_KEY }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_CENTRAL_GPG_PASSPHRASE }}
          # The following 2 env vars are used when uploading to Central
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }} # Must be the token "username", not the username for the UI
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }} # Must be the token "password", not the password for the UI
